### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by itspec-ru** [neutrinolabs/xorgxrdp#1]
In module/rdpClientCon.h included external headers
# include "xrdp_client_info.h"
# include "xrdp_constants.h"

placed in xrdp/common

Compilation output:

make  all-recursive
make[1]: Entering directory '/home/filatov/xorgxrdp'
Making all in module
make[2]: Entering directory '/home/filatov/xorgxrdp/module'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/X11/dri -I/usr/include/libdrm  -I../../common -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c -o rdpDraw.lo rdpDraw.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/X11/dri -I/usr/include/libdrm -I../../common -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c rdpDraw.c  -fPIC -DPIC -o .libs/rdpDraw.o
In file included from rdpDraw.c:44:0:
rdpClientCon.h:29:30: fatal error: xrdp_client_info.h: No such file or directory
 #include "xrdp_client_info.h"
                              ^
compilation terminated.
Makefile:473: recipe for target 'rdpDraw.lo' failed
make[2]: **\* [rdpDraw.lo] Error 1
make[2]: Leaving directory '/home/filatov/xorgxrdp/module'
Makefile:391: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/filatov/xorgxrdp'
Makefile:322: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by RussellAult** [comment]
Is there any way the source could be restructured so that the xorgxrdp repository can be compiled on its own? I'm currently trying to build Debian packages for xrdp for my own use (basically, I'm trying to avoid running compiled-from-source software on production machines) and making xorgxrdp a separate package seems to make a lot of sense, since it's based on a separate repository with separate versioning.

Thanks!

**Comment by proski** [comment]
I agree that we should fix it. I believe the best approach would be to install those headers as part of the xrdp install. Packagers can create a development package for xrdp (xrdp-dev in Debian, xrdp-devel in Fedora) and use it to compile xorgxrdp.

**Comment by proski** [comment]
xrdp has been fixed in git to install those headers. You should now be able to compile xorgxrdp in any directory, as long as the current version of xrdp is installed.

**Comment by metalefty** [comment]
Overcome by xrdp changes, closing.
